"""add tags to news

Revision ID: 2a9a9ef000ca
Revises: ddcbc861d4ab
Create Date: 2026-08-05 01:39:00.714762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9a9ef000ca'
down_revision: Union[str, Sequence[str], None] = 'ddcbc861d4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'tags')
    # ### end Alembic commands ###
